py-test:
  stage: test
  image: yourlabs/python-arch
  script:
  - pacman -Syu --noconfirm python-selenium geckodriver firefox
  - pip install pytest-splinter
  - python serve.py &
  - py.test -sv --splinter-headless

pages:
  stage: deploy
  image: node:alpine
  script:
  - sed -i 's@<head>@<head><base href="/autocomplete-light/">@' index.html
  - mkdir public
  - mv index.html autocomplete-light.js autocomplete-light.css public/
  artifacts:
    paths:
    - public
  only:
    refs:
      - master

pypi:
  stage: deploy
  script: pypi-release
  only: [tags]
