pages:
  stage: build
  image: node:alpine
  script:
  - npm install
  - npm run-script build
  - sed -i 's@<head>@<head><base href="/autocomplete-light/">@' www/index.html
  - mv www public
  artifacts:
    paths:
    - public
