/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AutocompleteLight {
        "choiceSelector": string;
        "hidden": boolean;
        "minimumCharacters": number;
        "url": string;
    }
    interface AutocompleteSelect {
        "maxChoices": number;
        "multiple": boolean;
        "name": string;
        "url": string;
    }
}
declare global {
    interface HTMLAutocompleteLightElement extends Components.AutocompleteLight, HTMLStencilElement {
    }
    var HTMLAutocompleteLightElement: {
        prototype: HTMLAutocompleteLightElement;
        new (): HTMLAutocompleteLightElement;
    };
    interface HTMLAutocompleteSelectElement extends Components.AutocompleteSelect, HTMLStencilElement {
    }
    var HTMLAutocompleteSelectElement: {
        prototype: HTMLAutocompleteSelectElement;
        new (): HTMLAutocompleteSelectElement;
    };
    interface HTMLElementTagNameMap {
        "autocomplete-light": HTMLAutocompleteLightElement;
        "autocomplete-select": HTMLAutocompleteSelectElement;
    }
}
declare namespace LocalJSX {
    interface AutocompleteLight {
        "choiceSelector"?: string;
        "hidden"?: boolean;
        "minimumCharacters"?: number;
        "url"?: string;
    }
    interface AutocompleteSelect {
        "maxChoices"?: number;
        "multiple"?: boolean;
        "name"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "autocomplete-light": AutocompleteLight;
        "autocomplete-select": AutocompleteSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "autocomplete-light": LocalJSX.AutocompleteLight & JSXBase.HTMLAttributes<HTMLAutocompleteLightElement>;
            "autocomplete-select": LocalJSX.AutocompleteSelect & JSXBase.HTMLAttributes<HTMLAutocompleteSelectElement>;
        }
    }
}
