/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AutocompleteLight {
        "boxContent": string;
        "choiceSelector": string;
        "minimumCharacters": number;
        "value": string;
    }
}
declare global {
    interface HTMLAutocompleteLightElement extends Components.AutocompleteLight, HTMLStencilElement {
    }
    var HTMLAutocompleteLightElement: {
        prototype: HTMLAutocompleteLightElement;
        new (): HTMLAutocompleteLightElement;
    };
    interface HTMLElementTagNameMap {
        "autocomplete-light": HTMLAutocompleteLightElement;
    }
}
declare namespace LocalJSX {
    interface AutocompleteLight {
        "boxContent"?: string;
        "choiceSelector"?: string;
        "minimumCharacters"?: number;
        "value"?: string;
    }
    interface IntrinsicElements {
        "autocomplete-light": AutocompleteLight;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "autocomplete-light": LocalJSX.AutocompleteLight & JSXBase.HTMLAttributes<HTMLAutocompleteLightElement>;
        }
    }
}
